"""Donna email tool — queues intake summary for attorney approval."""

import json
import os
import uuid
from datetime import datetime, timezone
from pathlib import Path

import httpx

DRAFTS_DIR = os.getenv("DONNA_DRAFTS_DIR", "/gbio/donna/drafts")
DASHBOARD_IPC_URL = os.getenv("DONNA_SESSION_ROUTER_URL", "http://localhost:8000/ipc")
ATTORNEY_EMAIL = os.getenv("DONNA_ATTORNEY_EMAIL", "anish.gup05@gmail.com")

TOOL_DEFINITIONS = [
    {
        "type": "function",
        "function": {
            "name": "send_intake_email",
            "description": (
                "Queue an intake summary email to the attorney for review and approval. "
                "Call this after create_case_file succeeds to notify the attorney of the new client."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "case_id": {
                        "type": "string",
                        "description": "Case ID returned by create_case_file",
                    },
                    "client_name": {"type": "string", "description": "Client full name"},
                    "incident_type": {
                        "type": "string",
                        "enum": ["auto_accident", "slip_fall", "workplace", "medical_malpractice", "other"],
                        "description": "Type of personal injury incident",
                    },
                    "incident_date": {
                        "type": "string",
                        "description": "Date of incident (YYYY-MM-DD)",
                    },
                    "incident_summary": {
                        "type": "string",
                        "description": "Brief description of what happened",
                    },
                    "injuries": {
                        "type": "string",
                        "description": "Injuries the client reported",
                    },
                    "attorney_email": {
                        "type": "string",
                        "description": "Override recipient — omit to use firm default",
                    },
                },
                "required": ["case_id", "client_name", "incident_summary"],
            },
        },
    },
]


def send_intake_email(
    case_id: str,
    client_name: str,
    incident_summary: str,
    incident_type: str = "other",
    incident_date: str = "",
    injuries: str = "",
    attorney_email: str = "",
) -> dict:
    to = attorney_email or ATTORNEY_EMAIL
    label = incident_type.replace("_", " ").title()
    subject = f"New Intake: {client_name} — {label}"
    body = (
        f"New client intake completed by Donna.\n\n"
        f"Client:        {client_name}\n"
        f"Case ID:       {case_id}\n"
        f"Incident Type: {label}\n"
        f"Incident Date: {incident_date or 'Not provided'}\n\n"
        f"Incident Summary:\n{incident_summary}\n\n"
        f"Injuries:\n{injuries or 'Not specified'}\n\n"
        "---\n"
        "Generated by Donna AI Legal Secretary\n"
        "All information stored locally on firm servers."
    )

    draft_id = str(uuid.uuid4())
    draft = {
        "draft_id": draft_id,
        "case_id": case_id,
        "status": "pending_approval",
        "email_type": "client_update",
        "to": to,
        "subject": subject,
        "body": body,
        "session_id": case_id,
        "created_at": datetime.now(timezone.utc).isoformat(),
        "donna_reasoning": "Auto-generated intake summary after case creation.",
    }

    drafts_path = Path(DRAFTS_DIR) / case_id
    drafts_path.mkdir(parents=True, exist_ok=True)
    (drafts_path / f"{draft_id}.json").write_text(json.dumps(draft, indent=2))

    _notify_sync(case_id, draft_id, to, subject, body[:200])

    return {
        "status": "queued",
        "draft_id": draft_id,
        "message": "Intake summary email queued for attorney review.",
    }


def _notify_sync(case_id: str, draft_id: str, to: str, subject: str, preview: str) -> None:
    try:
        with httpx.Client(timeout=3.0) as client:
            client.post(
                DASHBOARD_IPC_URL,
                json={
                    "source": "email",
                    "session_id": case_id,
                    "text": json.dumps({
                        "type": "email_draft_pending",
                        "draft_id": draft_id,
                        "case_id": case_id,
                        "to": to,
                        "subject": subject,
                        "email_type": "client_update",
                        "preview": preview,
                    }),
                    "type": "email_draft_pending",
                },
            )
    except Exception:
        pass
