from tools.calendar import TOOL_DEFINITIONS as CALENDAR_TOOLS
from tools.case_files import TOOL_DEFINITIONS as CASE_FILE_TOOLS
from tools.case_law import TOOL_DEFINITIONS as CASE_LAW_TOOLS

ALL_TOOL_DEFINITIONS = CALENDAR_TOOLS + CASE_FILE_TOOLS + CASE_LAW_TOOLS
